# This is a basic workflow to help you get started with Actions
name: CI

on:
  push:
    branches: [ "finalVersion" ]
    
jobs:
  Test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Simulator Control Panel
        run: javac -classpath "./jars/junit-4.11.jar";"./jars/hamcrest-core-1.3.jar";".test/team3" ./test/team3/Gryffindor/VM/SimulatorControlPanelTest.java
        shell: cmd
