# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ "finalVersion" ]
  pull_request:
    branches: [ "finalVersion" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
    - name: Run CustomerPanelTest
      run:
        cat ./test/team3/Gryffindor/VM/CustomerPanelTest.java
    - name: Run MachinerySimulatorPanelTest
      run:
        cat ./test/team3/Gryffindor/VM/MachinerySimulatorPanelTest.java
    - name: Run MaintainerPanelTest
      run:
        cat ./test/team3/Gryffindor/VM/MaintainerPanelTest.java
    - name: Run SimulatorControlPanelTest
      run:
        cat ./test/team3/Gryffindor/VM/SimulatorControlPanelTest.java
