# This is a basic workflow to help you get started with Actions
name: CI

on:
  push:
    branches:
      - finalVersion

jobs:
  test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Test
        run: |
          javac -d . "./src/team3/Gryffindor/VM/GUI/LayoutStrategy.java" "./src/team3/Gryffindor/VM/GUI/AfAnyWhereLayout.java" "./src/team3/Gryffindor/VM/GUI/AfMargin.java" "./src/team3/Gryffindor/VM/GUI/ButtonFactory.java" "./src/team3/Gryffindor/VM/GUI/T3Frame.java" "./src/team3/Gryffindor/VM/GUI/T3Panel.java" "./src/team3/Gryffindor/VM/GUI/TextUtils.java" "./src/team3/Gryffindor/VM/GUI/VerticalLayout.java" "./src/team3/Gryffindor/VM/model/NumberObserver.java"
          javac -d . "./src/team3/Gryffindor/VM/model/CoinIterator.java" "./src/team3/Gryffindor/VM/model/CheckKeyType.java" "./src/team3/Gryffindor/VM/model/ReadCSV.java" "./src/team3/Gryffindor/VM/model/WriteCSV.java" "./src/team3/Gryffindor/VM/model/TerminateMemento.java"
          javac -d . "./src/team3/Gryffindor/VM/model/CoinList.java" "./src/team3/Gryffindor/VM/model/DrinkList.java" "./src/team3/Gryffindor/VM/panel/CustomerPanel.java" "./src/team3/Gryffindor/VM/panel/MachinerySimulatorPanel.java" "./src/team3/Gryffindor/VM/panel/MaintainerPanel.java" "./src/team3/Gryffindor/VM/panel/SimulatorControlPanel.java"
          javac -d . -classpath "./jars/junit-4.11.jar";"./jars/hamcrest-core-1.3.jar"; "./test/team3/Gryffindor/VM/CustomerPanelTest.java" "./test/team3/Gryffindor/VM/MachinerySimulatorPanelTest.java" "./test/team3/Gryffindor/VM/MaintainerPanelTest.java" "./test/team3/Gryffindor/VM/SimulatorControlPanelTest.java"
          javac -classpath "./jars/junit-4.11.jar";"./jars/hamcrest-core-1.3.jar"; "./test/team3/Gryffindor/VM/JunitRunner.java"
          java -classpath "./jars/junit-4.11.jar";"./jars/hamcrest-core-1.3.jar"; "./test/team3/Gryffindor/VM/JunitRunner.java"

        shell: cmd